// Code generated by MockGen. DO NOT EDIT.
// Source: external.go

// Package warehouse is a generated GoMock package.
package warehouse

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentProvider is a mock of PaymentProvider interface.
type MockPaymentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentProviderMockRecorder
}

// MockPaymentProviderMockRecorder is the mock recorder for MockPaymentProvider.
type MockPaymentProviderMockRecorder struct {
	mock *MockPaymentProvider
}

// NewMockPaymentProvider creates a new mock instance.
func NewMockPaymentProvider(ctrl *gomock.Controller) *MockPaymentProvider {
	mock := &MockPaymentProvider{ctrl: ctrl}
	mock.recorder = &MockPaymentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentProvider) EXPECT() *MockPaymentProviderMockRecorder {
	return m.recorder
}

// ProcessPayment mocks base method.
func (m *MockPaymentProvider) ProcessPayment() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment")
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockPaymentProviderMockRecorder) ProcessPayment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockPaymentProvider)(nil).ProcessPayment))
}

// MockChartsNotifier is a mock of ChartsNotifier interface.
type MockChartsNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockChartsNotifierMockRecorder
}

// MockChartsNotifierMockRecorder is the mock recorder for MockChartsNotifier.
type MockChartsNotifierMockRecorder struct {
	mock *MockChartsNotifier
}

// NewMockChartsNotifier creates a new mock instance.
func NewMockChartsNotifier(ctrl *gomock.Controller) *MockChartsNotifier {
	mock := &MockChartsNotifier{ctrl: ctrl}
	mock.recorder = &MockChartsNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChartsNotifier) EXPECT() *MockChartsNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockChartsNotifier) Notify(title, artist string, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", title, artist, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockChartsNotifierMockRecorder) Notify(title, artist, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockChartsNotifier)(nil).Notify), title, artist, amount)
}
